name: Debug Build Android AAB

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show repository tree
        run: |
          echo "PWD:"
          pwd
          echo
          echo "Repository root:"
          ls -la
          echo
          echo "Recursive .github:"
          ls -R .github || true
          echo
          echo "Recursive flutter_app:"
          ls -R flutter_app || true
          echo
          echo "Find gradlew:"
          find . -name gradlew

      - name: Verify android directory
        run: |
          cd flutter_app/android
          pwd
          ls -la
          chmod +x gradlew
          ./gradlew --version