name: Repository Debug

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show Repository Structure
        run: |
          echo "PWD"
          pwd

          echo
          echo "Workspace"
          echo "$GITHUB_WORKSPACE"

          echo
          echo "Repository"
          find .

          echo
          echo "Gradle Wrappers"
          find . -name gradlew

          echo
          echo "Flutter Android"
          ls -la flutter_app/android || true